#!/bin/bash

# Update and install necessary packages
sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common expect

# Add Docker GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Add Docker repository
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Update the package database with Docker packages from the newly added repo
sudo apt-get update

# Install Docker
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

# Add the vagrant user to the docker group
sudo usermod -aG docker vagrant

# Enable Docker service
sudo systemctl enable docker
sudo systemctl start docker

# Pull the OpenVPN image
docker pull kylemanna/openvpn

# Create a Docker volume for OpenVPN data
docker volume create --name ovpn-data

# Generate the OpenVPN configuration
docker run -v ovpn-data:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u tcp://localhost:53504

./ovpn_initpki

# Start the OpenVPN server
docker run -v ovpn-data:/etc/openvpn -d -p 53504:1194/tcp --name ovpn-server --cap-add=NET_ADMIN kylemanna/openvpn
